version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'POSTGRESQL_DATABASE=strapi-plugin-example'
      - 'POSTGRESQL_USERNAME=postgres'
      - 'POSTGRESQL_PASSWORD=123456'

volumes:
  postgresql_data:
    driver: local
